import { MarketRecord } from './types';

export const DEMO_MARKET_RECORDS: MarketRecord[] = [
  {
    id: 'm1',
    state: 'Telangana',
    district: 'Adilabad',
    market: 'Adilabad APMC',
    commodity: 'Cotton',
    variety: 'Medium Staple',
    grade: 'FAQ',
    arrivalDate: '2026-10-02',
    minPrice: 6800,
    maxPrice: 7450,
    modalPrice: 7200,
  },
  {
    id: 'm2',
    state: 'Telangana',
    district: 'Adilabad',
    market: 'Bhaira APMC',
    commodity: 'Cotton',
    variety: 'Bunny/Brahma',
    grade: 'FAQ',
    arrivalDate: '2026-10-02',
    minPrice: 6900,
    maxPrice: 7600,
    modalPrice: 7350,
  },
  {
    id: 'm3',
    state: 'Maharashtra',
    district: 'Yavatmal',
    market: 'Yavatmal APMC',
    commodity: 'Cotton',
    variety: 'DCH-32',
    grade: 'Fine',
    arrivalDate: '2026-10-03',
    minPrice: 7100,
    maxPrice: 7850,
    modalPrice: 7520,
  },
  {
    id: 'm4',
    state: 'Telangana',
    district: 'Nizamabad',
    market: 'Nizamabad APMC',
    commodity: 'Soybean',
    variety: 'Yellow',
    grade: 'FAQ',
    arrivalDate: '2026-10-02',
    minPrice: 4200,
    maxPrice: 4750,
    modalPrice: 4550,
  },
  {
    id: 'm5',
    state: 'Madhya Pradesh',
    district: 'Indore',
    market: 'Indore Mandi',
    commodity: 'Soybean',
    variety: 'JS 9560',
    grade: 'FAQ',
    arrivalDate: '2026-10-03',
    minPrice: 4350,
    maxPrice: 4900,
    modalPrice: 4680,
  },
  {
    id: 'm6',
    state: 'Andhra Pradesh',
    district: 'Guntur',
    market: 'Guntur Mirchi Yard',
    commodity: 'Chili Red',
    variety: 'Teja',
    grade: 'Superior',
    arrivalDate: '2026-10-03',
    minPrice: 17500,
    maxPrice: 22000,
    modalPrice: 19800,
  },
  {
    id: 'm7',
    state: 'Telangana',
    district: 'Warangal',
    market: 'Warangal APMC',
    commodity: 'Maize',
    variety: 'Hybrid Yellow',
    grade: 'FAQ',
    arrivalDate: '2026-10-02',
    minPrice: 2050,
    maxPrice: 2320,
    modalPrice: 2240,
  },
  {
    id: 'm8',
    state: 'Karnataka',
    district: 'Kolar',
    market: 'Kolar APMC',
    commodity: 'Tomato',
    variety: 'Hybrid Round',
    grade: 'FAQ',
    arrivalDate: '2026-10-03',
    minPrice: 1200,
    maxPrice: 1800,
    modalPrice: 1500,
  },
  {
    id: 'm9',
    state: 'Punjab',
    district: 'Ludhiana',
    market: 'Khanna APMC',
    commodity: 'Paddy (Dhan)',
    variety: 'Basmati 1121',
    grade: 'FAQ',
    arrivalDate: '2026-10-01',
    minPrice: 3200,
    maxPrice: 3850,
    modalPrice: 3600,
  },
  {
    id: 'm10',
    state: 'Maharashtra',
    district: 'Nashik',
    market: 'Lasalgaon APMC',
    commodity: 'Onion',
    variety: 'Red',
    grade: 'FAQ',
    arrivalDate: '2026-10-03',
    minPrice: 1900,
    maxPrice: 2800,
    modalPrice: 2400,
  },
];
